### PR TITLE
fixes https://github.com/ska-sa/tigger/issues/99

### PR DESCRIPTION
**Pull request by o-smirnov**
Fixes https://github.com/ska-sa/tigger/issues/99.

Dunno why this didn't give an error before...

### CODE REVIEW

**Comment by o-smirnov** [comment]
@Athanaseus once this is in, we need to do a patch release of kittens, and that'll solve the tigger issue.

**Comment by o-smirnov** [comment]
@Athanaseus @gijzelaerr -- I've made a 1.4.1 release, could you please repackage and push into KERN and pypi.

**Comment by o-smirnov** [comment]
Not sure why the travis build is failing -- getting an obscure error towards the end, after all the test have passed.

**Comment by Athanaseus** [comment]
It is trying to upload the same old version to **pypi**. Since the version in [\_\_version\_\_](https://github.com/ska-sa/kittens/blob/master/Kittens/__init__.py`) was not incremented.

I think we should also add on tag deploy in .travis.yml. similar to [codex](https://github.com/ska-sa/codex-africanus/blob/master/.travis.yml#L27).

**Comment by o-smirnov** [comment]
Ah damn. Serves me right for trying to make a release myself. Could you please do it right?

**Comment by Athanaseus** [comment]
Oops ignore my second comment, it's already there.

I just made the version increment (1.4.2) and then we'll have to make a new release tag.

PS: Please add me to the repo, looks like I have permission issues.

**Comment by o-smirnov** [comment]
Added @Athanaseus.

**Pull request merged**
